<a href="https://colab.research.google.com/github/CuriousTechNomad/slm-agentic-software-engineering/blob/main/notebooks/02_swebench_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 02: SWE-Bench Lite Exploration

## Objective

This notebook explores the SWE-Bench Lite dataset, which will serve as the benchmark for evaluating our Small Language Model (SLM).

### Goals

- Download the dataset
- Understand its structure
- Inspect individual tasks
- Identify important fields
- Create a small evaluation subset
- Save the subset for future experiments

---
Project:
SLM Agentic Software Engineering

Author:
Shubham

In [ ]:
!pip -q install datasets pandas

In [ ]:
import json
import os

import pandas as pd

from pprint import pprint
from datasets import load_dataset

In [ ]:
dataset = load_dataset("princeton-nlp/SWE-bench_Lite")

README.md:   0%|          | 0.00/3.67k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/dev-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  120kB

data/dev-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 1.12MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating dev split:   0%|          | 0/23 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/300 [00:00<?, ? examples/s]

In [ ]:
print(dataset)

DatasetDict({
    dev: Dataset({
        features: ['repo', 'instance_id', 'base_commit', 'patch', 'test_patch', 'problem_statement', 'hints_text', 'created_at', 'version', 'FAIL_TO_PASS', 'PASS_TO_PASS', 'environment_setup_commit'],
        num_rows: 23
    })
    test: Dataset({
        features: ['repo', 'instance_id', 'base_commit', 'patch', 'test_patch', 'problem_statement', 'hints_text', 'created_at', 'version', 'FAIL_TO_PASS', 'PASS_TO_PASS', 'environment_setup_commit'],
        num_rows: 300
    })
})

In [ ]:
print("Number of tasks:", len(dataset["test"]))

Number of tasks: 300

In [ ]:
sample = dataset["test"][0]

print(type(sample))

<class 'dict'>

In [ ]:
print(sample.keys())

dict_keys(['repo', 'instance_id', 'base_commit', 'patch', 'test_patch', 'problem_statement', 'hints_text', 'created_at', 'version', 'FAIL_TO_PASS', 'PASS_TO_PASS', 'environment_setup_commit'])

In [ ]:
for key, value in sample.items():

    print("="*80)
    print(key)
    print("="*80)

    if isinstance(value, str):
        print(value[:500])
    else:
        print(value)

    print()

================================================================================
repo
================================================================================
astropy/astropy

================================================================================
instance_id
================================================================================
astropy__astropy-12907

================================================================================
base_commit
================================================================================
d16bfe05a744909de4b27f5875fe0d4ed41ce607

================================================================================
patch
================================================================================
diff --git a/astropy/modeling/separable.py b/astropy/modeling/separable.py
--- a/astropy/modeling/separable.py
+++ b/astropy/modeling/separable.py
@@ -242,7 +242,7 @@ def _cstack(left, right):
         cright = _coord_matrix(right, 'right', noutp)
     else:
         cright = np.zeros((noutp, right.shape[1]))
-        cright[-right.shape[0]:, -right.shape[1]:] = 1
+        cright[-right.shape[0]:, -right.shape[1]:] = right

     return np.hstack([cleft, cright])



================================================================================
test_patch
================================================================================
diff --git a/astropy/modeling/tests/test_separable.py b/astropy/modeling/tests/test_separable.py
--- a/astropy/modeling/tests/test_separable.py
+++ b/astropy/modeling/tests/test_separable.py
@@ -28,6 +28,13 @@
 p1 = models.Polynomial1D(1, name='p1')


+cm_4d_expected = (np.array([False, False, True, True]),
+                  np.array([[True,  True,  False, False],
+                            [True,  True,  False, False],
+                            [False, False, True,  False],
+

================================================================================
problem_statement
================================================================================
Modeling's `separability_matrix` does not compute separability correctly for nested CompoundModels
Consider the following model:

```python
from astropy.modeling import models as m
from astropy.modeling.separable import separability_matrix

cm = m.Linear1D(10) & m.Linear1D(5)
```

It's separability matrix as you might expect is a diagonal:

```python
>>> separability_matrix(cm)
array([[ True, False],
       [False,  True]])
```

If I make the model more complex:
```python
>>>

================================================================================
hints_text
================================================================================


================================================================================
created_at
================================================================================
2022-03-03T15:14:54Z

================================================================================
version
================================================================================
4.3

================================================================================
FAIL_TO_PASS
================================================================================
["astropy/modeling/tests/test_separable.py::test_separable[compound_model6-result6]", "astropy/modeling/tests/test_separable.py::test_separable[compound_model9-result9]"]

================================================================================
PASS_TO_PASS
================================================================================
["astropy/modeling/tests/test_separable.py::test_coord_matrix", "astropy/modeling/tests/test_separable.py::test_cdot", "astropy/modeling/tests/test_separable.py::test_cstack", "astropy/modeling/tests/test_separable.py::test_arith_oper", "astropy/modeling/tests/test_separable.py::test_separable[compound_model0-result0]", "astropy/modeling/tests/test_separable.py::test_separable[compound_model1-result1]", "astropy/modeling/tests/test_separable.py::test_separable[compound_model2-result2]", "astropy

================================================================================
environment_setup_commit
================================================================================
298ccb478e6bf092953bca67a3d29dc6c35f6752

In [ ]:
df = pd.DataFrame(dataset["test"])

df.head()

,repo,instance_id,base_commit,patch,test_patch,problem_statement,hints_text,created_at,version,FAIL_TO_PASS,PASS_TO_PASS,environment_setup_commit
0,astropy/astropy,astropy__astropy-12907,d16bfe05a744909de4b27f5875fe0d4ed41ce607,diff --git a/astropy/modeling/separable.py b/a...,diff --git a/astropy/modeling/tests/test_separ...,Modeling's `separability_matrix` does not comp...,,2022-03-03T15:14:54Z,4.3,"[""astropy/modeling/tests/test_separable.py::te...","[""astropy/modeling/tests/test_separable.py::te...",298ccb478e6bf092953bca67a3d29dc6c35f6752
1,astropy/astropy,astropy__astropy-14182,a5917978be39d13cd90b517e1de4e7a539ffaa48,diff --git a/astropy/io/ascii/rst.py b/astropy...,diff --git a/astropy/io/ascii/tests/test_rst.p...,Please support header rows in RestructuredText...,,2022-12-16T11:13:37Z,5.1,"[""astropy/io/ascii/tests/test_rst.py::test_rst...","[""astropy/io/ascii/tests/test_rst.py::test_rea...",5f74eacbcc7fff707a44d8eb58adaa514cb7dcb5
2,astropy/astropy,astropy__astropy-14365,7269fa3e33e8d02485a647da91a5a2a60a06af61,diff --git a/astropy/io/ascii/qdp.py b/astropy...,diff --git a/astropy/io/ascii/tests/test_qdp.p...,ascii.qdp Table format assumes QDP commands ar...,Welcome to Astropy 👋 and thank you for your fi...,2023-02-06T19:20:34Z,5.1,"[""astropy/io/ascii/tests/test_qdp.py::test_rou...","[""astropy/io/ascii/tests/test_qdp.py::test_get...",5f74eacbcc7fff707a44d8eb58adaa514cb7dcb5
3,astropy/astropy,astropy__astropy-14995,b16c7d12ccbc7b2d20364b89fb44285bcbfede54,diff --git a/astropy/nddata/mixins/ndarithmeti...,diff --git a/astropy/nddata/mixins/tests/test_...,"In v5.3, NDDataRef mask propagation fails when...",Welcome to Astropy 👋 and thank you for your fi...,2023-06-27T19:48:18Z,5.2,"[""astropy/nddata/mixins/tests/test_ndarithmeti...","[""astropy/nddata/mixins/tests/test_ndarithmeti...",362f6df12abf9bd769d4915fabf955c993ea22cf
4,astropy/astropy,astropy__astropy-6938,c76af9ed6bb89bfba45b9f5bc1e635188278e2fa,diff --git a/astropy/io/fits/fitsrec.py b/astr...,diff --git a/astropy/io/fits/tests/test_checks...,Possible bug in io.fits related to D exponents...,It is tested with `astropy/io/fits/tests/test_...,2017-12-07T00:01:14Z,1.3,"[""astropy/io/fits/tests/test_checksum.py::Test...","[""astropy/io/fits/tests/test_checksum.py::Test...",848c8fa21332abd66b44efe3cb48b72377fb32cc

In [ ]:
df["repo"].value_counts().head(20)

repo
django/django                114
sympy/sympy                   77
scikit-learn/scikit-learn     23
matplotlib/matplotlib         23
pytest-dev/pytest             17
sphinx-doc/sphinx             16
pylint-dev/pylint              6
astropy/astropy                6
psf/requests                   6
pydata/xarray                  5
mwaskom/seaborn                4
pallets/flask                  3
Name: count, dtype: int64

In [ ]:
df["problem_length"] = df["problem_statement"].apply(len)

df["problem_length"].describe()

count      300.000000
mean      1661.176667
std       2447.983340
min        230.000000
25%        626.000000
50%       1043.500000
75%       1868.500000
max      24770.000000
Name: problem_length, dtype: float64

In [ ]:
subset = dataset["test"].select(range(5))

In [ ]:
for task in subset:

    print("="*80)
    print(task["instance_id"])
    print(task["repo"])
    print(task["problem_statement"][:250])
    print()

================================================================================
astropy__astropy-12907
astropy/astropy
Modeling's `separability_matrix` does not compute separability correctly for nested CompoundModels
Consider the following model:

```python
from astropy.modeling import models as m
from astropy.modeling.separable import separability_matrix

cm

================================================================================
astropy__astropy-14182
astropy/astropy
Please support header rows in RestructuredText output
### Description

It would be great if the following would work:

```Python
>>> from astropy.table import QTable
>>> import astropy.units as u
>>> import sys
>>> tbl = QTable({'wave': [350,

================================================================================
astropy__astropy-14365
astropy/astropy
ascii.qdp Table format assumes QDP commands are upper case
### Description

ascii.qdp assumes that commands in a QDP file are upper case, for example, for errors they must be "READ SERR 1 2" whereas QDP itself is not case sensitive and case use "read

================================================================================
astropy__astropy-14995
astropy/astropy
In v5.3, NDDataRef mask propagation fails when one of the operand does not have a mask
### Description

This applies to v5.3.

It looks like when one of the operand does not have a mask, the mask propagation when doing arithmetic, in particular wi

================================================================================
astropy__astropy-6938
astropy/astropy
Possible bug in io.fits related to D exponents
I came across the following code in ``fitsrec.py``:

```python
        # Replace exponent separator in floating point numbers
        if 'D' in format:
            output_field.replace(encode_ascii(

In [ ]:
os.makedirs("/content/project_outputs", exist_ok=True)

subset_list = [dict(task) for task in subset]

with open("/content/project_outputs/swebench_subset.json", "w") as f:
    json.dump(subset_list, f, indent=2)

print("Subset saved successfully.")

Subset saved successfully.

In [ ]:
summary = df[
    [
        "instance_id",
        "repo",
        "problem_statement"
    ]
]

summary.to_csv(
    "/content/project_outputs/swebench_summary.csv",
    index=False
)

print("Summary saved.")

Summary saved.

# Observations

### Dataset

- SWE-Bench Lite consists of real GitHub software engineering tasks.
- Each task includes an issue description and the corresponding ground-truth patch.
- Tasks span multiple popular open-source repositories.

### Importance

The benchmark allows reproducible evaluation of software engineering capabilities.

### Next Step

Run the baseline Small Language Model on selected tasks.

In [ ]:
print("="*60)
print("Notebook 02 completed successfully.")
print("="*60)

============================================================
Notebook 02 completed successfully.
============================================================